MentalHealthApp.WebApp/Controllers/ForumController.cs
using MentalHealthApp.BusinessLogic.Implementation;
using MentalHealthApp.BusinessLogic.Implementation.Admin;
using MentalHealthApp.BusinessLogic.Implementation.Forum.ViewModels;
using MentalHealthApp.Entities.Enums;
using MentalHealthApp.WebApp.Code.Base;
using Microsoft.AspNetCore.Mvc;

namespace MentalHealthApp.WebApp.Controllers
{
    public class ForumController : BaseController
    {
        private readonly ForumService _forumService;
        private readonly HomePageService _homeService;
       public ForumController(ControllerDependencies dependencies,
                              ForumService forumService,
                              HomePageService homePageService)
                             : base(dependencies)
        { 
            _forumService = forumService;
            _homeService = homePageService;
        }



        [HttpGet]
        public IActionResult ViewForumFirstPage(int page)
        {
            if(page < 0)
            {
                page = 0;
            }
            int pageSize = 6;
            var conditions = _homeService.GetConditionsName();
            var discussionsList = _forumService.GetAllDiscussions(page*pageSize, pageSize);
            var model = new CreateDiscussionVM()
            {
                DiscussionVMs = discussionsList.Select(app => new DiscussionVM
                {
                    UserId = app.UserId,
                    Username = app.Username,
                    Id = app.Id,
                    Titlu = app.Titlu,
                    Continut = app.Continut,
                    DataCreare = app.DataCreare,
                    UserImage = app.UserImage,

                }).ToList(),
                Conditions = conditions.ToList(),
                Page = page

            };

            return View("ForumFirstPage", model);
        }
        [HttpPost]
        public async Task<IActionResult> CreateDiscussion(CreateDiscussionVM model)
        {

            _forumService.CreateDiscussion(model);
           // return View("ForumFirstPage", model);
            return RedirectToAction("ViewForumFirstPage");
        }

/// 
        [HttpGet]
        public IActionResult ViewDiscussion(Guid id)
        {
            var discussionDetails = _forumService.GetDiscussionById(id);
            var comments = _forumService.ViewDiscussionComments(id);
            var model = new DiscussionVM()
            {
                Id = discussionDetails.Id,
                UserId = discussionDetails.UserId,
                Username = discussionDetails.Username,
                Titlu = discussionDetails.Titlu,
                Continut = discussionDetails.Continut,
                DataCreare = discussionDetails.DataCreare,
                UserImage = discussionDetails.UserImage,
                CommentReaction = discussionDetails.CommentReaction,
                createDiscussionCommentsVMs = comments.Select(app => new CreateDiscussionCommentsVM
                {
                    Id = app.Id,
                    UserId = app.UserId,
                    DiscutieId = id,
                    DiscussionTitle = app.DiscussionTitle,
                    Username = app.Username,
                    Continut = app.Continut,
                    DataComentariu = app.DataComentariu,
                    CommentReaction = app.CommentReaction,
                    UserImage = app.UserImage
                }).ToList()
            };
            return View("DiscussionPage", model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateDiscussionComment(DiscussionVM model)
        {
            if(!ModelState.IsValid)
            {
                return Json("Discutia nu este adecvata");
            }
            _forumService.CreateDiscussionComment(model);
            return RedirectToAction("ViewDiscussion", new {id = model.Id});
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteDiscussion(Guid id, Guid user)
        {
            var role =  _forumService.GetRole((Guid)CurrentUser.Id);
            if (user.Equals(CurrentUser.Id) || role.Equals(RoleTypes.Admin.ToString()))
            {
                var model = await _forumService.DeleteDiscussion(id);
                return Ok(model.Id);
            }
            return StatusCode(StatusCodes.Status401Unauthorized, "You can not proceed with the action");
        }
        [HttpDelete]
        public async Task<IActionResult> DeleteComment(Guid id, Guid user)
        {
            var role = _forumService.GetRole((Guid)CurrentUser.Id);
            if (user.Equals(CurrentUser.Id) || role.Equals(RoleTypes.Admin.ToString()))
            {
                var model = await _forumService.DeteleComment(id);
                return Ok(model.Id);
            }
            return StatusCode(StatusCodes.Status401Unauthorized);

        }

		[HttpGet]
        public IActionResult NumberOfComments(Guid id)
		{
            var comments =  _forumService.NumberOfComments(id);
            return Ok(comments);
		}
        [HttpPatch]
        public IActionResult EditComment(Guid id, string message, Guid user)
        {
            if (!ModelState.IsValid)
            {
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
            var role = _forumService.GetRole((Guid)CurrentUser.Id);
            if (user.Equals(CurrentUser.Id) || role.Equals(RoleTypes.Admin.ToString()))
            {
                var newMessage = _forumService.EditComment(id, message);
                return Ok(newMessage);
            }
            return Ok();
        }

        [HttpPatch]
        public IActionResult AdDiscussionReaction(Guid id)
        {
            _forumService.AddDiscussionReaction(id);
            return Ok();
        }


        [HttpPatch]
        public IActionResult AddCommentReaction(Guid id)
        {
            _forumService.AddReaction(id);
            return Ok();
        }
        [HttpPatch]
        public IActionResult DeleteReaction(Guid id)
        {

            _forumService.DeleteReaction(id);
            return Ok();
        }

        [HttpPatch]
        public IActionResult EditDiscussionMainComment(Guid id, string message, Guid user)
        {
            if (!ModelState.IsValid)
            {
                return StatusCode(StatusCodes.Status500InternalServerError);
            }
            var role = _forumService.GetRole((Guid)CurrentUser.Id);
            if (user.Equals(CurrentUser.Id) || role.Equals(RoleTypes.Admin.ToString()))
            {
                var newMessage = _forumService.EditDiscussionContent(id, message);
                return Ok(newMessage);
            }
            return Ok();
        }
    }
}

MentalHealthApp.WebApp/Controllers/MedicalReportsController.cs
using MentalHealthApp.BusinessLogic.Implementation.MedicalReports;
using MentalHealthApp.BusinessLogic.Implementation.MedicalReports.ViewModels;
using MentalHealthApp.WebApp.Code.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MentalHealthApp.WebApp.Controllers
{
    public class MedicalReportsController : BaseController
    {
        private readonly MedicalReportService _medicalReport;
        public MedicalReportsController(ControllerDependencies dependencies,
                                         MedicalReportService medicalReportsService) : base(dependencies)
        {
            _medicalReport = medicalReportsService;
        }

        [Authorize(Roles = "Specialist")]
        [HttpGet]
        public IActionResult CreateMedicalReport()
        {
            var model = new DoctorMedicalReportVM();
            return View("CreateMedicalReport", model);
        }

        [Authorize(Roles = "Specialist")]
        [HttpPost]
        public IActionResult CreateMedicalReport(DoctorMedicalReportVM model)
        {
            if (!ModelState.IsValid)
            {
                return View("Error");
            }
            _medicalReport.CreateMedicalReport(model);
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Pacient")]
        [HttpGet]
        public IActionResult ViewMedicalHistory()
        {
            var model = _medicalReport.ViewUserMedicalHistory();
            return View("UserHistory", model);
        }

        [Authorize(Roles = "Pacient")]
        [HttpGet]
        public IActionResult ViewAReport(Guid id)
        {
            var model = _medicalReport.ViewMedicalHistoryById(id);

            return View("MedicalReportView", model);
        }
    }
}

MentalHealthApp.WebApp/Controllers/ProfileController.cs
using AutoMapper;
using MentalHealthApp.BusinessLogic.Implementation;
using MentalHealthApp.BusinessLogic.Implementation.Account;
using MentalHealthApp.BusinessLogic.Implementation.Account.Validations;
using MentalHealthApp.BusinessLogic.Implementation.Account.ViewModels;
using MentalHealthApp.BusinessLogic.Implementation.Appointments.ViewModels;
using MentalHealthApp.Common.DTOs;
using MentalHealthApp.DataAccess;
using MentalHealthApp.Entities.Enums;
using MentalHealthApp.WebApp.Code.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MentalHealthApp.WebApp.Controllers
{
    public class ProfileController : BaseController
    {
        private readonly UserProfileService _userProfileService;
        private readonly DoctorAccountService _doctorAccountService;
        private readonly ProgramareService _programareService;
        private readonly IMapper _mapper;
        public ProfileController(ControllerDependencies dependencies,
                                UserProfileService userProfileService,
                                DoctorAccountService doctorAccountService,
                                IMapper mapper,
                                ProgramareService programareService
                                )
                                : base(dependencies)
        {
            _userProfileService = userProfileService;
            _doctorAccountService = doctorAccountService;
            _mapper = mapper;
            _programareService = programareService;
        }

        [HttpGet]
        public async  Task<IActionResult> UserProfile()
        {
            var profile =  await _userProfileService.GetUserByEmail(CurrentUser.Email);
            return View(profile);
    
        }

        [HttpPost]
        public IActionResult EditUserProfile(UserVM model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var userDto = _mapper.Map<EditUserDto>(model);
            _userProfileService.EditUserInfo(userDto);
            return RedirectToAction("UserProfile", model);
        }
        [HttpGet]
        public async Task<IActionResult> EditUserProfile(string email)
        {
            var model = await _userProfileService.GetUserByEmail(email);
            return View("EditUserProfile",model);
        }

        [HttpPatch]
        public  IActionResult ChangeProfilePhoto(IFormFile userImage)
        {
            var model =  _userProfileService.ChangeProfilePhoto(userImage);
            return Ok(userImage);
        }
        [HttpGet]
        //[Authorize(Roles = "Specialist")]
        public async Task<IActionResult> DoctorProfile()
        {
            var profile = await _doctorAccountService.GetDoctorByEmail(CurrentUser.Email);
            return View("DoctorAccountProfile", profile);

        }
        //[HttpGet]
        //public  IActionResult DoctorsProfile()
        //{
        //    var profile = _doctorAccountService.GetDoctorsInfo();
        //    return View("DoctorsProfile", profile);

        //}
        [HttpGet]
        public IActionResult DoctorsProfile(int page)
        {
            if (page < 0)
            {
                page = 0;
            }
            int pageSize = 9;
            var doctorCards = _doctorAccountService.GetDoctorsInfo(page*pageSize, pageSize);
            var model = (doctorCards, page);
            return View("DoctorsProfile", model);

        }
        [HttpGet]
        public IActionResult UserProfileMap()
        {
            return View("UserProfileMap");

        }
        [HttpGet]
        public async Task<IActionResult> DoctorInfo(string email)
        {
            var profile = await  _doctorAccountService.GetDoctorByEmail(email);
           // var model = _mapper.Map<DoctorVM>(profile);
            return View("DoctorInfo", profile);

        }
        [HttpGet]
        public async Task<IActionResult> DoctorInfoById(Guid id)
        {
            var profile = await _doctorAccountService.GetDoctorById(id);
            // var model = _mapper.Map<DoctorVM>(profile);
            return View("DoctorInfo", profile);

        }

        [HttpGet]
        public IActionResult Appointments(Guid id)
        {

            var listaProgramari = _programareService.GetAppointments();
            var listaData = _programareService.GetAcceptedAppointmentsOnPage(id);
            var lista = _doctorAccountService.GetDoctorProgram(id);
            var model = new AppointmentModel()
            {

                SpecialistId = id,
                AppointmentsVMs = listaProgramari.Select(app => new AppointmentsVM
                {
                    Id = app.Id,
                    DataProgramare = app.DataProgramare,
                    Doctor = app.Doctor,
                    TipProgramare = app.TipProgramare,
                    StareProgramare = app.StareProgramare

                }).ToList(),
                AcceptedAppointmentsData = listaData.Select(ld => new AppointmentsDoctorProfileVM
                {
                    DataProgramare = ld.DataProgramare
                }).ToList(),
                DoctorWorkProgramVMs  = lista.Select(dwp => new DoctorWorkProgramVM
                {
                    Id = dwp.Id,
                    SpecialistId = dwp.SpecialistId,
                    WorkDayId = dwp.WorkDayId,
                    WorkDay = dwp.WorkDay,
                    Start = dwp.Start,
                    End = dwp.End,
                    Notes = dwp.Notes
                }).ToList()
            };
 
            return View("Appointments", model);

        }

        [HttpGet]
        public IActionResult UserTodayAppointments()
        {
            var appointments = _programareService.GetUserTodayAppointments();
            var model = new AcceptedAppointmentsVM()
            {


                AcceptedAppointmentsVMs = appointments.Select(app => new AcceptedAppointmentsVM
                {
                    Id = app.Id,
                    DataProgramare = app.DataProgramare,
                    Specialist = app.Specialist,
                    Email = app.Email,
                    PhoneNumber = app.PhoneNumber,
                    UserImage = app.UserImage

                }).ToList()
            };
            return View("UserTodayAppointments", model);
        }
    }
}

MentalHealthApp.WebApp/Controllers/ProspectController.cs
using MentalHealthApp.WebApp.Code.Base;
using Microsoft.AspNetCore.Mvc;

namespace MentalHealthApp.WebApp.Controllers
{
    public class ProspectController : BaseController
    {

        public ProspectController(
                              ControllerDependencies dependencies) : base(dependencies)
        {}

        [HttpGet]
        public IActionResult MedicationSearch()
        {
            return View("MedicationSearch");
        }

    }
}

MentalHealthApp.WebApp/Views/Shared/_Layout.cshtml
@inject MentalHealthApp.Common.DTOs.CurrentUserDto CurrentUser
@using System.Security.Claims
@*@inject MentalHealthApp.Common.DTOs.EditUserDto user*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MentalHealthApp.WebApp</title>
    <script src="https://kit.fontawesome.com/bdd89edb33.js"></script>
      <script src="https://kit.fontawesome.com/049529442a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MentalHealthApp.WebApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/layout.css"/>  
</head>
<!--dust particel-->

<body>
    <div>
  <div class="starsec"></div>
  <div class="starthird"></div>
  <div class="starfourth"></div>
  <div class="starfifth"></div>
</div>
    <header style="padding: 0px">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3 " style="background: radial-gradient(ellipse at bottom, #f1b866 0%, #e75757 100%); box-shadow:0.3rem 0.5rem 0.95rem rgb(247 242 242 / 20%);">
            <div class="container-fluid">
                  <img style="  z-index: 99999; width: 38px; max-height: 80%;  max-width: 80%;" class="preloader-logo" src="~/images/Logo.png" width=90>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hygieia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        @{
                            if (CurrentUser.isAuthenticated)
                            {
                                                                    
                                                                    
                                    var role = User.Claims.Where(c => c.Type == ClaimTypes.Role).FirstOrDefault().Value;
                                    if (role == "Pacient" || role == "Specialist")
                                    {
                                                    <li class="nav-item">
                                                        <a class="nav-link text-dark" asp-controller="Forum" asp-action="ViewForumFirstPage" asp-route-page="0">Forum</a>
                                                        </li>
                                         
                                        
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-action="DoctorsProfile" asp-controller="Profile"  asp-route-page='0' >Medici</a>
                                        </li>
                                          <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-action="MedicationSearch" asp-controller="Prospect"  >Prospect Medical</a>
                                        </li>
                                }
                                if(role == "Pacient")
                                  {
                                                    <li class="nav-item">
                                                            <a class="nav-link text-dark" asp-controller="Profile" asp-action="UserProfile" >Profil</a>
                                                        </li>
                                }
}
                            }
                            @{
                           if (CurrentUser.isAuthenticated)
                            {
                              var role = User.Claims.Where(c => c.Type == ClaimTypes.Role).FirstOrDefault().Value;
                                           @if (role == "Admin")
                                {
                           
                                                <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Dashboard">Administrare</a>
                                            </li>
                                }
                        }
                                              
                           if (CurrentUser.isAuthenticated)
                            {
                              var role = User.Claims.Where(c => c.Type == ClaimTypes.Role).FirstOrDefault().Value;
                                          @if (role == "Specialist")
                            {
                                             <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-controller="MedicalReports" asp-action="CreateMedicalReport" >Creaza Raport</a>
                                            </li>
                                            <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-controller="Profile" asp-action="DoctorProfile" >Profil</a>
                                            </li>
                                            <div class="dropdown">
                                                    <li style="color:black" value="Programari" class="dropbtn">Programari</li>
                                                <div class="dropdown-content">
                                                        <a asp-area="" asp-controller="DoctorAccount" asp-action="PhysicalAppointments">Fizic</a>
                                                        <a asp-area="" asp-controller="DoctorAccount" asp-action="OnlineAppointments">Online</a>
                                                </div>
                                            </div> 
                             

                                }
                        }
                        }
                        
                    </ul>
                </div>    
                    @{
                    if(CurrentUser.isAuthenticated)
                    {
                       
                                            <p style="flex-shrink: 0;  margin-right:3px;  margin-bottom: 0;">@CurrentUser.FirstName</p> 
                              
		                        var base64 = Convert.ToBase64String(@CurrentUser.UserImage);                  
		                        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
		                        if(@imgSrc == "data:image/gif;base64,")
		                        {
                                                <img style="flex-shrink: 0;   margin-bottom: 0;  z-index: 99999;  height: 50px; width: 50px; max-height: 80%; object-fit:cover; max-width: 80%; margin-left:5px border-radius: 50%;" class="img-lg rounded-circle border shadow"  src="~/images/Userprofile.jpg" alt="">
		                        }
		                        else{
                                                <img  width=120  style="flex-shrink: 0;   margin-bottom: 0;  z-index: 99999;  height: 50px; width: 50px; max-height: 80%; object-fit:cover; margin-left:5px;  max-width: 80%; border-radius: 50%;" class="img-lg rounded-circle border shadow"  src="@imgSrc" alt="" />
		                        }
              

                                                                        <div style="flex-shrink: 0;  margin-right: 2%; font-size: 1.4rem;  margin-bottom: 0;  z-index: 99999;" class="dropdown">
                                                                            <a   value="Programari" class="dropbtn"><i class="fa fa-bars"></i></a>
                                                                        <div class="dropdown-content" style=" margin-left: -40px;">
                                                                                <a asp-controller="UserAccount" asp-action="Logout"> Log Out</a>
                                                                        </div>
                                                                        </div>
                    }
                    else
                    {
                                        <div class="dropdown" style="flex-shrink: 0;  margin-right: 2%; font-size: 1.4rem;  margin-bottom: 0;  z-index: 99999;">
                                        <a class="dropbtn"><i class="fa fa-bars"></i></a>
                                    <div class="dropdown-content" style="font-size: 0.9rem;  margin-left: -40px;" >
                                            <a asp-controller="UserAccount" asp-action="Login"> Log In</a>
                                            <a asp-controller="UserAccount" asp-action="Register">Register User</a>
                                    </div>
                                </div> 
                                            
                                          
                            }

                            }                                      
                    </nav>
                    </header>
                    <div class="container" style="padding-bottom: 65px; max-width: 1500px;"> 
                        <main role="main" class="pb-3">
                            @RenderBody()
                        </main>
                    </div>



                        <footer class="border-top footer text-muted" style="line-height: 50px;">
                            <div class="container">
                                &copy; 2022 - Hygieia - Mental Health is not a taboo <i class="fa-light fa-head-side-heart" style="color: red; font-size: 1.6rem"></i>
                            </div>
                        </footer>
                        <script src="~/lib/jquery/dist/jquery.min.js"></script>
                        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
                        <script src="~/js/site.js" asp-append-version="true"></script>
                        @await RenderSectionAsync("Scripts", required: false)
                    </body>
                    </html>


 @*<script>
    window.addEventListener("load", function() {
        document.getElementById("ProfileImage").src = localStorage.getItem("image");
    });
 </script>*@