MentalHealthApp.WebApp/Controllers/UserAccountController.cs
using MentalHealthApp.BusinessLogic.Implementation;
using MentalHealthApp.BusinessLogic.Implementation.Account;
using MentalHealthApp.BusinessLogic.Implementation.Account.Validations;
using MentalHealthApp.BusinessLogic.Implementation.Account.ViewModels;
using MentalHealthApp.Common.DTOs;
using MentalHealthApp.Common.Extensions;
using MentalHealthApp.WebApp.Code;
using MentalHealthApp.WebApp.Code.Base;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace MentalHealthApp.WebApp.Controllers
{
    public class UserAccountController : BaseController
    {
        private readonly UserAccountService _userAccountService;
        private readonly ForumService _forumService;
        public UserAccountController(ControllerDependencies dependencies, UserAccountService userAccountService)
            :base(dependencies)
        {
            this._userAccountService = userAccountService;
        }

        private async Task LogIn(CurrentUserDto user)
        {
            var claims = new List<Claim>
            {
                new Claim("Id", user.Id.ToString()),
                new Claim(ClaimTypes.Name, $"{user.FirstName} {user.LastName}"),
                new Claim(ClaimTypes.Email, user.Email)
            };
            user.Roles.ForEach(role => claims.Add(new Claim(ClaimTypes.Role, role)));
            var identity = new ClaimsIdentity(claims, "Cookies");
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(
                scheme: "MentalHealthAppCookies",
                principal: principal
                );
        }

        private async  Task LogOut()
        {
            await HttpContext.SignOutAsync(scheme: "MentalHealthAppCookies");
        }

        [HttpGet]
        public IActionResult Login()
        {
            var model = new LoginModel();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginModel model)
        {
            var user = _userAccountService.Login(model.Email, model.Password);
            if (user is null)
            {
                ModelState.AddModelError(nameof(LoginModel.Password), "Email/Password incorrect");
                return View(model);
            }

            if (!user.isAuthenticated)
            {
                model.AreCredentialsInvalid = true;
                return View(model);
            }
            await LogIn(user);
           // var role = _forumService.GetRole(user.Id ?? Guid.Empty);
            //if (role.Equals(RoleTypes.Pacient.ToString()))
            //{
            //    return RedirectToAction("UserProfile", "Profile");
            //}
            //else
            //{
                return RedirectToAction("Index", "Home");
            //}

        }

        [HttpGet]
        public async Task<ActionResult> Logout()
        {
            await LogOut();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult DemoPage()
        {
            var model = _userAccountService.GetUsers();
            return View(model);
        }

        [HttpGet] 
        public IActionResult Register()
        {
            var model = new RegisterModel();
            return View("Register", model);
        }

        [HttpPost]

        public IActionResult Register(RegisterModel model)
        {
            //if(!ModelState.IsValid)
            //{
            //    ModelState.AddModelError(nameof(LoginModel), "Date invalide");
            //}
            _userAccountService.RegisterNewUser(model);
            return RedirectToAction("Index", "Home");
        }

       
    }
}

MentalHealthApp.WebApp/Views/UserAccount/DemoPage.cshtml
@model List<MentalHealthApp.Common.DTOs.ListItemModel<string, Guid>>
@{
    ViewData["Title"] = "Login";
}



<h1>Login</h1>



<h4>LoginModel</h4>
<hr />
<div class="form-group"></div>
<div class="row">
    <label class="control-label">User</label>
    <select class="form-control" asp-items="@(new SelectList(Model, "Value", "Text"))"></select>
</div>

MentalHealthApp.WebApp/Views/UserAccount/Login.cshtml
@model MentalHealthApp.BusinessLogic.Implementation.Account.ViewModels.LoginModel 
@{
    ViewData["Title"] = "Login";
}



<h1>Login</h1>



<h4>LoginModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @if (Model.AreCredentialsInvalid)
        {
            <div><span style="color:red">Invalid credentials</span></div>
        }
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



<div>
    <a asp-action="Index">Back to List</a>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


MentalHealthApp.WebApp/Views/UserAccount/Register.cshtml
@model MentalHealthApp.BusinessLogic.Implementation.Account.ViewModels.RegisterModel
@using MentalHealthApp.Entities.Enums
@{
    ViewData["Title"] = "View";
}

<head>
<link rel="stylesheet" type="text/css" href="~/css/dropdownAppointments.css">
</head>

<h1>Register User</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Register" asp-controller="UserAccount">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Nume</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">Prenume</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="BirthDate" class="control-label">Data nastere</label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
               <div class="form-group">
                <label asp-for="PhoneNumberCountryPrefix" class="control-label">Prefix telefonic</label>
                <input asp-for="PhoneNumberCountryPrefix" class="form-control" />
                <span asp-validation-for="PhoneNumberCountryPrefix" class="text-danger"></span>
            </div>
               <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label">Numar Contact</label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
               <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
               <div class="form-group">
                <label asp-for="Categorie" class="control-label"></label>
                <span class="custom-dropdown big" >
                    <select style="background:white" asp-for="Categorie" class="form-control"  id="description">    
                            <option>@Categories.Angajat.ToString()</option>
                            <option>@Categories.Elev.ToString()</option>
                            <option>@Categories.Student.ToString()</option>
                            <option>@Categories.Pensionar.ToString()</option>
                    </select>
                </span>
                <span asp-validation-for="Categorie" class="text-danger"></span>
            </div>
               <div class="form-group">
                <label asp-for="Asigurat" class="control-label">Asigurare medicala</label>
                <span class="custom-dropdown big" >
                                                <select style="background:white" asp-for="Asigurat" class="form-control"  id="description">    
                                                        <option>Da</option>
                                                        <option>Nu</option>
                                                    </select>
                                            </span>
                <span asp-validation-for="Asigurat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordHash" class="control-label">Parola</label>
                <input asp-for="PasswordHash" type="password" class="form-control" />
                <span asp-validation-for="PasswordHash" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tara" class="control-label"></label>
                <input asp-for="Tara" class="form-control" />
                <span asp-validation-for="Tara" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Judet" class="control-label"></label>
                <input asp-for="Judet" class="form-control" />
                <span asp-validation-for="Judet" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Oras" class="control-label"></label>
                <input asp-for="Oras" class="form-control" />
                <span asp-validation-for="Oras" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StradaNumar" class="control-label">Strada, Numar</label>
                <input asp-for="StradaNumar" class="form-control" />
                <span asp-validation-for="StradaNumar" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="BlocScaraApartament" class="control-label">Bloc, Scara, Apartament</label>
                <input asp-for="BlocScaraApartament" class="form-control" />
                <span asp-validation-for="BlocScaraApartament" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="Sector" class="control-label"></label>
                <input asp-for="Sector" class="form-control" />
                <span asp-validation-for="Sector" class="text-danger"></span>
            </div>
              <div class="form-group">
                <label asp-for="CodPostal" class="control-label">Cod Postal</label>
                <input asp-for="CodPostal" class="form-control" />
                <span asp-validation-for="CodPostal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserImage" class="control-label">Imagine Profil</label>
                <input asp-for="UserImage" type="file" class="form-control" />
                <span asp-validation-for="UserImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



<div>
    <a asp-action="Index">Back to List</a>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}