MentalHealthApp.WebApp/Controllers/DoctorAccountController.cs
using MentalHealthApp.BusinessLogic.Implementation;
using MentalHealthApp.BusinessLogic.Implementation.Account;
using MentalHealthApp.BusinessLogic.Implementation.Account.ViewModels;
using MentalHealthApp.BusinessLogic.Implementation.Appointments.ViewModels;
using MentalHealthApp.Entities.Enums;
using MentalHealthApp.WebApp.Code.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MentalHealthApp.WebApp.Controllers
{
    public class DoctorAccountController : BaseController
    {
        private readonly ProgramareService _programareService;
        private readonly DoctorAccountService _doctorAccountService;
        public DoctorAccountController(ControllerDependencies dependencies,
                                       ProgramareService programareService,
                                       DoctorAccountService doctorAccountService) 
                                       : base(dependencies) 
        {
            _programareService = programareService;
            _doctorAccountService = doctorAccountService;
        }

        [Authorize(Roles = "Specialist")]
        [HttpGet]
        public IActionResult AwaitingAppointments()
        {
            var appointments =  _programareService.GetAllAwaitingAppointments();
            var model = new AppointmentsDoctorProfileVM()
            {


                AppointmentDoctorProfileVMs = appointments.Select(app => new AppointmentsDoctorProfileVM
                {
                    Id = app.Id,
                    DataProgramare = app.DataProgramare,
                    Pacient = app.Pacient,
                    StareProgramare = app.StareProgramare
                }).ToList()
            };
            return View("AwaitingAppointments", model);
        }

        [Authorize(Roles = "Specialist")]
        [HttpGet]
        public IActionResult OnlineAppointments()
        {
            var appointments = _programareService.GetAllOnlineAppointments();
            var model = new AcceptedAppointmentsVM()
            {


                AcceptedAppointmentsVMs = appointments.Select(app => new AcceptedAppointmentsVM
                {
                    Id = app.Id,
                    DataProgramare = app.DataProgramare,
                    Pacient = app.Pacient,
                    BirthDate = app.BirthDate,
                    Email = app.Email,
                    PhoneNumber = app.PhoneNumber,
                    Categorie = app.Categorie,
                    Asigurat = app.Asigurat,
                    StareProgramare = app.StareProgramare,
                    UserImage = app.UserImage
                    
                }).ToList()
            };
            return View("OnlineAppointments", model);
        }

        [Authorize(Roles = "Specialist")]
        [HttpGet]
        public IActionResult PhysicalAppointments()
        {
            var appointments = _programareService.GetAllPhysicalAppointments();
            var model = new AcceptedAppointmentsVM()
            {


                AcceptedAppointmentsVMs = appointments.Select(app => new AcceptedAppointmentsVM
                {
                    Id = app.Id,
                    DataProgramare = app.DataProgramare,
                    Pacient = app.Pacient,
                    BirthDate = app.BirthDate,
                    Email = app.Email,
                    PhoneNumber = app.PhoneNumber,
                    Categorie = app.Categorie,
                    Asigurat = app.Asigurat,
                    StareProgramare = app.StareProgramare

                }).ToList()
            };
            return View("PhysicalAppointments", model);
        }

        [Authorize(Roles = "Specialist")]
        [HttpGet]
        public IActionResult TodayAppointments()
        {
            var appointments = _programareService.GetTodayAppointments();
            var model = new AcceptedAppointmentsVM()
            {


                AcceptedAppointmentsVMs = appointments.Select(app => new AcceptedAppointmentsVM
                {
                    Id = app.Id,
                    DataProgramare = app.DataProgramare,
                    Pacient = app.Pacient,
                    BirthDate = app.BirthDate,
                    Email = app.Email,
                    PhoneNumber = app.PhoneNumber,
                    Categorie = app.Categorie,
                    Asigurat = app.Asigurat,
                    UserImage = app.UserImage

                }).ToList()
            };
            return View("TodayAppointments", model);
        }

        [Authorize(Roles = "Specialist")]
        [HttpPost]
        public IActionResult AcceptAppointment(int appointmentId, string stare)
        {
            var result = _programareService.EditStatus(appointmentId, stare);
            return Ok(stare);
        }

        [Authorize(Roles = "Specialist")]
        [HttpGet]
        public IActionResult NumberOfAppointments()
        {
            var appointments = _programareService.AwaitingAppoinments();
            return Ok(appointments);
        }

        [Authorize(Roles = "Specialist")]
        [HttpPost]
        public  IActionResult AddWorkProgram(DoctorWorkProgramVM model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("WorkProgram");
            }
            _doctorAccountService.AddWorkProgram(model);
            return RedirectToAction("WorkProgram");
        }

       
        [HttpGet]
        public IActionResult WorkProgram()
        {
            var lista = _doctorAccountService.GetProgram();
            var workDays = _doctorAccountService.GetWorkDays();
           
            var model = new DoctorWorkProgramVM()
            {
                DoctorWorkProgramVMs = lista.Select(dwp => new DoctorWorkProgramVM
                {
                    Id = dwp.Id,
                    SpecialistId = dwp.SpecialistId,
                    WorkDayId = dwp.WorkDayId,
                    WorkDay = dwp.WorkDay,
                    Start = dwp.Start,
                    End = dwp.End,
                    Notes = dwp.Notes

                }).ToList(),
                workDaysVMs = workDays.Select(wd => new WorkDaysVM
                {
                    Id = wd.Id,
                    Name = wd.Name
                }).ToList()
            };
            return View("WorkProgram", model);
        }
    }
}

MentalHealthApp.WebApp/Controllers/OnlineAppointmentController.cs
using AutoMapper;
using MentalHealthApp.BusinessLogic.Implementation;
using MentalHealthApp.BusinessLogic.Implementation.Account;
using MentalHealthApp.BusinessLogic.Implementation.Admin;
using MentalHealthApp.WebApp.Code.Base;
using Microsoft.AspNetCore.Mvc;

namespace MentalHealthApp.WebApp.Controllers
{
    public class OnlineAppointmentController : BaseController
    {
        private readonly ForumService _forum;
        private readonly IMapper _mapper;
        public OnlineAppointmentController(ControllerDependencies dependencies,
                               ForumService forum,
                               IMapper mapper)
            : base(dependencies)
        {
            _mapper = mapper;
            _forum = forum;

        }

        [HttpGet]
        public IActionResult VideoDiscussion(int id)
        {
            var role = _forum.GetRole((Guid)CurrentUser.Id);
            ViewData["IsInitiator"] = role == "Specialist";
            ViewData["id"] = id;
            return View("VideoDiscussion");
        }

    }
}

MentalHealthApp.WebApp/Views/DoctorAccount/AwaitingAppointments.cshtml
@model MentalHealthApp.BusinessLogic.Implementation.Appointments.ViewModels.AppointmentsDoctorProfileVM
@using MentalHealthApp.Entities.Enums
<header>
    	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
       	<link rel="stylesheet" href="https://fontawesome.com/releases/v5.10.0/css/all.css">
        <link rel="stylesheet" href="~/css/onlineAppointment.css"/>
</header>

<body>

  <div class="page-header">
    <h3>Programari online in asteptare</h3>
  </div>

 <div>
   <table class="table table-bordered table-hover table-striped table-sm" id="appointment_list">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" class="text-center align-middle">Id Programare</th>
                            <th scope="col" class="text-center align-middle">Data</th>
                            <th scope="col" class="text-center align-middle">Pacient</th>
                            <th scope="col" class="text-center align-middle">Status</th>
                            <th scope="col" class="text-center align-middle">Actiune</th>


              @foreach(var programare in @Model.AppointmentDoctorProfileVMs)
                {
                    <tr id="status-@programare.Id">
                        <td>@programare.Id</td>
                        <td>@programare.DataProgramare</td>
                        <td>@programare.Pacient</td>
                        <td id="status-@programare.Id" >
                            <p id="status-td-@programare.Id">@programare.StareProgramare</p>
                         <div  id="edit-@programare.Id" style="display:none" >
                                         <span class="custom-dropdown big" >
                                                <select id="div-dropdown-@programare.Id">    
                                                        <option>@AppointmentStatus.In_Asteptare.ToString()</option>
                                                        <option>@AppointmentStatus.Programare_Respinsa.ToString()</option>
                                                        <option>@AppointmentStatus.Programare_Acceptata.ToString()</option>
                                                        <option>@AppointmentStatus.Programare_Anulata.ToString()</option>
                                                        <option>@AppointmentStatus.Programare_Realizata.ToString()</option>
                                                    </select>
                                            </span>
								<button class="btn btn-std mb-link" style="background-color:rgb(169,146,209)"  onclick="SaveStatus()" id="@programare.Id">Salveaza</button>
						</div>
                        </td>

                        <td>
                              <button  onclick="AcceptAppointment()" id="@programare.Id" ><i class="fa fa-check" title="Accept"></i></button>
                              <button onclick="EditAppointmentStatus()" id="@programare.Id"  ><i class="fa fa-pen" title="Edit Status" aria-hidden="true"></i></button>
                        </td>
                    </tr>
                }
            </thead>
                    <tbody>
                    </tbody>
                </table>
</div>
</body>
<script>
     function AcceptAppointment(){
    
        const id = event.srcElement.id;
         $.ajax({
             url: '@Url.Action("AcceptAppointment", "DoctorAccount")',

             type: "POST",

             data: { appointmentId: id },
             success: function(data) {
                 console.log("Success");
                 alert("Programare acceptata cu succes");
                 document.getElementById('status-' + id).remove();
             },

             error: function(response) {
                 console.log("Error");
                 console.log(JSON.stringify(response));
             }
         });
};
function EditAppointmentStatus() {
     let id = event.srcElement.parentNode.id;
    let td = document.getElementById("status-td-" + id);
    td.style.display = "none";
    let select = document.getElementById("edit-" + id);
    select.style.display = "block";
}

function SaveStatus() {
    const id = event.srcElement.id;
    const dropdownValue = document.getElementById("div-dropdown-"+id).value;
     $.ajax({
             url: '@Url.Action("AcceptAppointment", "DoctorAccount")',

             type: "POST",

             data: { appointmentId: id, stare:dropdownValue },
             success: function(data) {
                 alert("Status programare schimbat cu succes");
                 document.getElementById('status-' + id).remove();
             },

             error: function(response) {
                 console.log("Error");
                 console.log(JSON.stringify(response));
             }
         });
}
</script>

MentalHealthApp.WebApp/Views/DoctorAccount/OnlineAppointments.cshtml
@model MentalHealthApp.BusinessLogic.Implementation.Appointments.ViewModels.AcceptedAppointmentsVM
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Appointment Cards</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
	<link rel="stylesheet" type="text/css" href="~/css/style.css">
</head>
<body>
	<section class="main-content">
		<div class="container">
			<h1>Programari Online</h1>
			<br>
			<br>

			<div class="row">
				 @foreach(var programare in @Model.AcceptedAppointmentsVMs)
                {
					<div class="col-sm-6 col-md-6 col-lg-4">
						<div class="card bg-white p-3 mb-4 shadow">
							<div class="d-flex justify-content-between mb-4">
								<div class="user-info">
									<div class="user-info__img">
										@{
														var base64 = Convert.ToBase64String(@programare.UserImage);                  
														var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
														if(imgSrc == "data:image/gif;base64,"){
																	<img src="~/images/Userprofile.jpg" alt="">
														}
														else{
																 	<img  src="@imgSrc" alt="" />
														}
												
												}
									</div>
									<div class="user-info__basic">
										<h5 class="mb-0">@programare.Pacient</h5>
										<p class="text-muted mb-0">@programare.BirthDate, Categorie: @programare.Categorie </p>
											<p class="text-muted mb-0">Asigurat: @programare.Asigurat </p>
									</div>
								</div>
								<div class="dropdown open">
									<a href="#!" class="px-2" id="triggerId1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										<i class="fa fa-ellipsis-v"></i>
									</a>
									<div class="dropdown-menu" aria-labelledby="triggerId1">
										<a class="dropdown-item" href="#"><i class="fa fa-pencil mr-1"></i> Edit</a>
										<a class="dropdown-item text-danger" href="#"><i class="fa fa-trash mr-1"></i> Delete</a>
									</div>
								</div>
							</div>
							<h6 class="mb-0">@programare.PhoneNumber</h6>
							<h6 class="mb-0">@programare.Email</h6>
							<a href="#!"><small>Contact</small></a>
							<div class="d-flex justify-content-between mt-4">
								<div>
									<h5 class="mb-0">
										<small class="ml-1">@programare.DataProgramare</small>
									</h5>
								</div>
								<span class="text-success font-weight-bold">@programare.StareProgramare</span>
							</div>
						</div>
					</div>
				}
			
		</div>
	</section>
	
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

MentalHealthApp.WebApp/Views/DoctorAccount/PhysicalAppointments.cshtml
@model MentalHealthApp.BusinessLogic.Implementation.Appointments.ViewModels.AcceptedAppointmentsVM
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Appointment Cards</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
	<link rel="stylesheet" type="text/css" href="~/css/style.css">
</head>
<body>
	<section class="main-content">
		<div class="container">
			<h1>Programari Fizice</h1>
			<br>
			<br>

			<div class="row">
				 @foreach(var programare in @Model.AcceptedAppointmentsVMs)
                {
					<div class="col-sm-6 col-md-6 col-lg-4">
						<div class="card bg-white p-3 mb-4 shadow">
							<div class="d-flex justify-content-between mb-4">
								<div class="user-info">
									<div class="user-info__img">
										<img src="~/images/Userprofile.jpg" alt="User Img">
									</div>
									<div class="user-info__basic">
										<h5 class="mb-0">@programare.Pacient</h5>
										<p class="text-muted mb-0">@programare.BirthDate, Categorie: @programare.Categorie </p>
											<p class="text-muted mb-0">Asigurat: @programare.Asigurat </p>
									</div>
								</div>
								<div class="dropdown open">
									<a href="#!" class="px-2" id="triggerId1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										<i class="fa fa-ellipsis-v"></i>
									</a>
									<div class="dropdown-menu" aria-labelledby="triggerId1">
										<a class="dropdown-item" href="#"><i class="fa fa-pencil mr-1"></i> Edit</a>
										<a class="dropdown-item text-danger" href="#"><i class="fa fa-trash mr-1"></i> Delete</a>
									</div>
								</div>
							</div>
							<h6 class="mb-0">@programare.PhoneNumber</h6>
							<h6 class="mb-0">@programare.Email</h6>
							<a href="#!"><small>Contact</small></a>
							<div class="d-flex justify-content-between mt-4">
								<div>
									<h5 class="mb-0">
										<small class="ml-1">@programare.DataProgramare</small>
									</h5>
								</div>
								<span class="text-success font-weight-bold">@programare.StareProgramare</span>
							</div>
						</div>
					</div>
				}
			
		</div>
	</section>
	
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

MentalHealthApp.WebApp/Views/DoctorAccount/TodayAppointments.cshtml
@model MentalHealthApp.BusinessLogic.Implementation.Appointments.ViewModels.AcceptedAppointmentsVM
@using MentalHealthApp.Entities.Enums
<head>
	<meta charset="UTF-8">
	<title>Appointment Cards</title>
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
	<link rel="stylesheet" type="text/css" href="~/css/style.css">
</head>

	<section class="main-content">
		<div class="container">
			<br>
			<br>

			<div class="row">
				 @foreach(var programare in @Model.AcceptedAppointmentsVMs)
                {
					<div class="col-sm-6 col-md-6 col-lg-4" id="Appcard-@programare.Id">
						<div class="card bg-white p-3 mb-4 shadow">
							<div class="d-flex justify-content-between mb-4">
								<div class="user-info">
									<div class="user-info__img">
										@{ 
											 var base64 = Convert.ToBase64String(programare.UserImage);                  
											 var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
											 if(@imgSrc == "data:image/gif;base64,")
											 {
													<img src="~/images/Userprofile.jpg" alt="User Img">														
											 }
											 else{
													<img src="@imgSrc" alt="User Img">																									  
											 }
										 } 
									</div>
									<div class="user-info__basic">
										<h5 class="mb-0">@programare.Pacient</h5>
										<p class="text-muted mb-0">  Categorie: @programare.Categorie</p>
											<p class="text-muted mb-0">Asigurat: @programare.Asigurat </p>
									</div>
								</div>
								<div>
									<a data-button="@programare.Id" class="btn" onclick="changeStatus(@programare.Id)"  asp-action="VideoDiscussion" asp-controller="OnlineAppointment" asp-route-id="@programare.Id" id="conference-button-@programare.Id" >
										<i  data-i="@programare.Id" class="fa fa-video" ></i>
									</a>
								</div>
							</div>
							<h6 class="mb-0">@programare.PhoneNumber</h6>
							<h6 class="mb-0">@programare.Email</h6>
							<a href="#!"><small>Contact</small></a>
							  <p id="status-td-@programare.Id">@AppointmentStatus.Programare_Acceptata.ToString()</p>
							  <button onclick="ShowDropdown()" id="@programare.Id"  ><i class="fa fa-pen" title="Edit Status" aria-hidden="true"></i></button>
							<div  id="edit-@programare.Id" style="display:none" >
                                         <span class="custom-dropdown big" >
                                                <select id="div-dropdown-@programare.Id">    
                                                        <option>@AppointmentStatus.Programare_Anulata.ToString()</option>
                                                        <option>@AppointmentStatus.Programare_Realizata.ToString()</option>
                                                    </select>
                         </span>
								<button class="btn btn-std mb-link" style="background-color:rgb(169,146,209)"  onclick="SaveStatus()" id="@programare.Id">Salveaza</button>
							</div>
							<div class="d-flex justify-content-between mt-4">
								<div>
									<h5 class="mb-0 data-programare" id="hour-@programare.Id" data="@programare.Id">@programare.DataProgramare.Split("T")[1]</h5>
								</div>
							</div>
						</div>
					</div>
				}
			
		</div>
	</section>
	
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

<script>
	function ShowDropdown() {
     let id = event.srcElement.id;
    let td = document.getElementById("status-td-" + id);
    td.style.display = "none";
    let select = document.getElementById("edit-" + id);
    select.style.display = "block";
}
function SaveStatus() {
    const id = event.srcElement.id;
    const dropdownValue = document.getElementById("div-dropdown-"+id).value;
     $.ajax({
             url: '@Url.Action("AcceptAppointment", "DoctorAccount")',

             type: "POST",

             data: { appointmentId: id, stare:dropdownValue },
             success: function(data) {
                 alert("Status programare schimbat cu succes");
                  document.getElementById("Appcard-" + id).remove();
             },

             error: function(response) {
                 console.log("Error");
                 console.log(JSON.stringify(response));
             }
         });
}
function changeStatus(id) {
		 const stare = "Programare_Realizata";
         $.ajax({
             url: '@Url.Action("AcceptAppointment", "DoctorAccount")',

             type: "POST",

             data: { appointmentId: id, stare:stare },
             success: function(data) {
                 document.getElementById("Appcard-" + id).remove();
             },

             error: function(response) {
                 console.log(JSON.stringify(response));
             }
         })
};
window.addEventListener("load", function() {
    let div_data = document.getElementsByClassName("data-programare");
	const date = new Date(Date.now());
    const currentDate =date.getHours().toString() + ":" + date.getMinutes().toString();
    for (let i = 0; i < div_data.length; i++) {
        let id = div_data[i].getAttribute("data");
        if (div_data[i].innerHTML >= currentDate.toString() ) {
			let buton = document.getElementById("conference-button-" + id);
            buton.removeAttribute("disabled");
            return;
        }
    }
});

</script>

MentalHealthApp.WebApp/Views/DoctorAccount/WorkProgram.cshtml
@model MentalHealthApp.BusinessLogic.Implementation.Account.ViewModels.DoctorWorkProgramVM
<head>
    <link  rel="stylesheet" href="~/css/createAppointments.css"/>
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">

     <script src="~/js/appointment/viewAppoinments.js"></script>
 </head>  

  <body> 
   
        <div class="row">
            <div class="col offset-md-1">
                <form asp-action="AddWorkProgram" asp-controller="DoctorAccount">
                        <div class="col form-group">
                            <label asp-for="WorkDay" class="required">Date</label>
                            <span class="custom-dropdown big" >
                            <select id="div-dropdown" asp-for="WorkDay">    
                                    @foreach(var day in @Model.workDaysVMs)
                                    {

                                        <option>@day.Name</option>
                                    }
                                </select>
                            </span>
                           <span asp-validation-for="WorkDay" class="text-danger"></span>
                        </div>
       
                        <div class="col form-group">
                            <label asp-for="Start" class="required">Ora Inceput</label>
                             <input asp-for="Start" class="form-control" type="text" id="description">
                             <span asp-validation-for="Start" class="text-danger"></span>
                    </div>
                      <div class="col form-group" >
                            <label asp-for="End" class="control-label">Ora Sfarsit</label>
                            <input asp-for="End" class="form-control" type="text" id="description"/>
                           <span asp-validation-for="End" class="text-danger"></span>
                        </div>
                         <div class="col form-group" >
                            <label asp-for="Notes" class="control-label">Descriere suplimentara</label>
                            <input asp-for="Notes" class="form-control" type="text" id="description"/>
                           <span asp-validation-for="Notes" class="text-danger"></span>
                        </div>
                        <div></div>
                    <div class="form-row">
                        <div class="col form-group">
                            <button type="submit" value="Save" class="btn btn-primary" id="submit">Add Work Program</button>
                        </div>
                    </div>
                </form>
            </div>


            <div class="col offset-md-1">
                <div class="row">
                    <div class="col">
                    </div>
                </div>
                <table class="table table-bordered table-hover table-striped table-sm" id="appointment_list">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" class="text-center align-middle">Work Day</th>
                            <th scope="col" class="text-center align-middle">Start</th>
                            <th scope="col" class="text-center align-middle">End</th>
                            <th scope="col" class="text-center align-middle">Notes</th>

              @foreach(var program in @Model.DoctorWorkProgramVMs)
                {
                    <tr >
                        <td>@program.WorkDay</td>
                        <td>@program.Start</td>
                        <td>@program.End</td>
                        <td>@program.Notes</td>
                    </tr>
                }
            </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            </div>
 
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  
</body>